/* No imports, fetches, CDN assets or server: also works from file://. */
'use strict';
const $=id=>document.getElementById(id);
const ru={}; document.querySelectorAll('[data-i18n]').forEach(e=>ru[e.dataset.i18n]=e.innerHTML);
Object.assign(ru,{emblems:'ВМК МГУ · Факультет вычислительной математики и кибернетики',authorName:'Капитонов Станислав · Корж Евгения',authorDetails:'ВМК МГУ. Фотографии авторов и официальная эмблема факультета ещё не добавлены.',supervisor:'Преподаватель-руководитель: Чичигина Ольга Александровна.'});
const en={brand:'FLUCTUATIONS / LAB',offline:'● Works offline',home:'Home',lab:'Presentation',theory:'Theory',authors:'Authors',exit:'Exit',course:'STATISTICAL PHYSICS · INTERACTIVE EXPERIMENT',title:'Stochastic<br>resonance',intro:'When noise helps you hear a signal.',intro2:'Explore a particle in a double-well potential: a weak periodic signal, random kicks, and the order that emerges between them.',open:'Start exploring →',read:'How it works →',bistable:'TWO STATES. ONE WEAK SIGNAL.',feat1:'Observe',feat1p:'Particle, potential and signal on the same timeline.',feat2:'Control the noise',feat2p:'Compare weak, moderate and strong noise.',feat3:'Test the resonance',feat3p:'Measure the response directly from simulated trajectories.',emblems:'CMC MSU · Faculty of Computational Mathematics and Cybernetics',experiment:'01 / NUMERICAL EXPERIMENT',labTitle:'Find the useful noise',parameters:'System parameters',seed:'Random seed',resetHint:'Changing a parameter starts a new realization with the same seed.',weak:'Weak',medium:'Moderate',strong:'Strong',speed:'Playback speed',slow:'Slow ×1',fast:'Fast ×15',start:'Start',pause:'Pause',stop:'Stop',export:'Download trajectory CSV ↓',potential:'Particle in the potential',transitions:'Transitions',trajectory:'Trajectory and driving force',axesHint:'All quantities are dimensionless. Position: left axis; force: right axis. Last 3 periods.',sweepHeading:'02 / TEST THE HYPOTHESIS',sweepTitle:'More noise — stronger response?',sweep:'Measure resonance',cancel:'Cancel',csv:'CSV ↓',sweepInfo:'12 noise levels × 6 realizations. Each: 4 warm-up periods and 16 measured periods. Points: amplitude of the mean response at the driving frequency; whiskers: ±1 standard error.',sweepCaution:'An interior maximum indicates stochastic resonance; it is not guaranteed for arbitrary parameters. Finite samples have statistical uncertainty. This is not a signal-to-noise ratio plot.',theoryHeading:'FROM OBSERVATION TO MODEL',project:'STUDENT PROJECT',authorName:'Stanislav Kapitonov · Evgeniya Korzh',authorDetails:'CMC MSU. Author photographs and the official faculty emblem have not been added yet.',supervisor:'Academic supervisor: Olga Alexandrovna Chichigina.',sourceCredit:'Based on O. A. Chichigina, “Fluctuation Processes”, lecture notes, §12.6.',footer:'STOCHASTIC RESONANCE · LEARNING LAB'};
let lang='ru',p={...Physics.defaults},model=new Physics.Model(p),running=false,history=[],sweepData=[],sweepParams=null,sweepToken=0,sweeping=false,noticeKey='',sweepState='idle';
const text=(a,b)=>lang==='ru'?a:b;
function theory(){return lang==='ru'?`
<h3>Почему шум может помочь?</h3><p>Без шума слабая периодическая сила обычно не выводит частицу из одной ямы. Умеренный шум делает переходы через барьер возможными, а внешняя сила задаёт предпочтительные моменты этих переходов. При слишком сильном шуме переходы становятся менее согласованными с сигналом. В подходящем диапазоне параметров отклик имеет максимум при ненулевой интенсивности шума.</p>
<h3>Модель из §12.6 конспекта</h3><div class="equation">V(x) = −x²/2 + x⁴/8<br>dx = v dt<br>dv = [x − x³/2 − γv + f sin(ωt)] dt + √(2D) dWₜ</div><p>Масса равна единице. Белый шум определён соглашением ⟨ξ(t)ξ(t′)⟩ = 2D δ(t−t′). Все переменные и параметры безразмерные. При равновесии эффективная температура равна D/γ. Это важно: D здесь — интенсивность случайной силы, а не непосредственно температура.</p><p>Минимумы V расположены в x = ±√2, барьер ΔV = 1/2. На графике показан мгновенный потенциал U(x,t) = V(x) − f x sin(ωt); наклон соответствует внешней силе. Статическая сила исчезновения барьера fс = (2/3)√(2/3) ≈ 0,544. Ползунок f ограничен значением 0,5. Это условие сохранения двух ям, а не гарантия отсутствия динамических переходов без шума.</p>
<h3>Времена переходов и резонанс</h3><p>Качественный ориентир — среднее время межъямного перехода порядка половины периода сигнала: τ ≈ π/ω. В пределе сильного трения и малого шума оценка Крамерса для невозмущённого потенциала: τ ≈ (2πγ/√2) exp(γ/(2D)). Для инерционной системы при умеренном трении этот префактор неточен; приложение определяет отклик численно и не подгоняет график под эту формулу.</p>
<h3>Что измеряет эксперимент?</h3><div class="equation">aⱼ = (2/T) ∫ xⱼ(t) sin(ωt) dt<br>bⱼ = (2/T) ∫ xⱼ(t) cos(ωt) dt<br>A = √(⟨a⟩² + ⟨b⟩²)</div><p>После 4 периодов разогрева интегрируем в течение 16 периодов, усредняем коэффициенты по 6 независимым реализациям и находим амплитуду среднего отклика. Для каждого уровня D используем другие зёрна генератора. Усы показывают стандартную ошибку по дельта-методу; при почти нулевой амплитуде эта оценка приближённая. Максимум по конечной сетке не даёт точного значения оптимального шума. Амплитуда отклика и отношение сигнал/шум — разные характеристики.</p>
<h3>Численный метод и управление</h3><p>Используется расщепление BAOAB: сила, перенос координаты, точный шаг Орнштейна—Уленбека для скорости, перенос, сила. Нормальный шум получается преобразованием Бокса—Мюллера из воспроизводимого генератора Mulberry32. Основной шаг Δt = 0,02; быстрый показ меняет только число шагов за секунду, но не шаг интегрирования.</p><p>«Старт» продолжает расчёт, «Пауза» сохраняет состояние, «Стоп» останавливает и сбрасывает траекторию. Изменение физического параметра или зерна также сбрасывает расчёт и результаты измерения. Счётчик переходов использует пороги x = ±0,7, чтобы не считать повторные пересечения вершины барьера. CSV траектории содержит последние 3 периода, CSV отклика — завершённые точки и параметры. Для проверки сходимости тесты сравнивают Δt = 0,02 и 0,01.</p>
<h3>Сценарий демонстрации</h3><ol><li>Откройте презентацию и выберите слабый шум. Наблюдайте колебания в одной яме.</li><li>Выберите умеренный шум и быстрый темп: переходы чаще согласуются с периодическим наклоном.</li><li>Выберите сильный шум: регулярность переходов ухудшается.</li><li>Верните умеренный шум и запустите измерение резонанса. Оцените максимум с учётом погрешностей.</li></ol>`:`
<h3>Why can noise help?</h3><p>A weak periodic force usually leaves a noiseless particle trapped in one well. Moderate noise enables barrier crossings, while the periodic drive favors particular transition times. Excessive noise reduces this synchronization. For suitable parameters the response peaks at a nonzero noise intensity.</p>
<h3>Model from lecture §12.6</h3><div class="equation">V(x) = −x²/2 + x⁴/8<br>dx = v dt<br>dv = [x − x³/2 − γv + f sin(ωt)] dt + √(2D) dWₜ</div><p>Unit mass; white-noise convention ⟨ξ(t)ξ(t′)⟩ = 2D δ(t−t′). All quantities are dimensionless. The equilibrium effective temperature is D/γ: D is the random-force intensity, not the temperature itself.</p><p>The minima are x = ±√2 and the barrier is ΔV = 1/2. The plot shows U(x,t) = V(x) − f x sin(ωt). The static barrier disappears at fс = (2/3)√(2/3) ≈ 0.544. We restrict f ≤ 0.5; retaining two wells does not rule out deterministic dynamical transitions.</p>
<h3>Transition times</h3><p>A qualitative matching condition is τ ≈ π/ω, half the forcing period. For strong damping and weak noise, the unforced Kramers estimate is τ ≈ (2πγ/√2) exp(γ/(2D)). Its prefactor is inaccurate at moderate damping; the experiment measures the response numerically instead of fitting this formula.</p>
<h3>Measured response</h3><div class="equation">aⱼ = (2/T) ∫ xⱼ(t) sin(ωt) dt<br>bⱼ = (2/T) ∫ xⱼ(t) cos(ωt) dt<br>A = √(⟨a⟩² + ⟨b⟩²)</div><p>Discard 4 warm-up periods, measure 16 periods, then average the Fourier coefficients over 6 independent realizations. Seeds differ across noise levels. Whiskers show delta-method standard errors, approximate near zero amplitude. A finite-grid maximum is not an exact optimum. Response amplitude is distinct from signal-to-noise ratio.</p>
<h3>Numerics and controls</h3><p>BAOAB splitting combines force kicks, coordinate drifts and an exact Ornstein–Uhlenbeck velocity step. Box–Muller Gaussian noise uses seeded Mulberry32 uniform samples. Δt = 0.02; faster playback changes steps per second, not the integration step.</p><p>Start resumes; Pause preserves state; Stop resets the trajectory. Changing a physical parameter or seed also clears the measurement. Transitions use hysteresis at x = ±0.7 to exclude immediate barrier recrossings. Trajectory CSV exports the last 3 periods; response CSV exports completed points and parameters. Convergence tests compare Δt = 0.02 and 0.01.</p>
<h3>Presentation guide</h3><ol><li>Choose weak noise: observe motion within one well.</li><li>Choose moderate noise and fast playback: transitions tend to follow the drive.</li><li>Choose strong noise: synchronization deteriorates.</li><li>Return to moderate noise and measure the response curve. Interpret the peak together with its uncertainty.</li></ol>`;}
function translate(){document.documentElement.lang=lang;document.title=text('Стохастический резонанс · Лаборатория','Stochastic resonance · Lab');document.querySelectorAll('[data-i18n]').forEach(e=>e.innerHTML=(lang==='ru'?ru:en)[e.dataset.i18n]);$('language').textContent=lang==='ru'?'EN':'RU';$('theoryContent').innerHTML=theory()+`<h3>${text('Источники','References')}</h3><ol><li><a href="http://www.ilc.msu.ru/learning/multimedia/FPAllbook.pdf" target="_blank" rel="noreferrer">${text('О. А. Чичигина. Флуктуационные процессы. §12.6, с. 103–105.','O. A. Chichigina. Fluctuation Processes. §12.6, pp. 103–105.')}</a></li><li><a href="https://doi.org/10.1103/RevModPhys.70.223" target="_blank" rel="noreferrer">Gammaitoni et al. Stochastic resonance. Rev. Mod. Phys. 70, 223 (1998).</a></li><li><a href="https://doi.org/10.1093/amrx/abs010" target="_blank" rel="noreferrer">Leimkuhler & Matthews. Rational Construction of Stochastic Numerical Methods for Molecular Sampling (2013).</a></li></ol>`;renderControls();updateStatus();updateNotice();updateSweepStatus();draw();}
const labels={D:['Интенсивность шума D','Noise intensity D'],f:['Амплитуда силы f','Force amplitude f'],omega:['Частота ω','Angular frequency ω'],gamma:['Трение γ','Damping γ']};
function renderControls(){ $('parameters').innerHTML=''; for(const [k,[r,e]] of Object.entries(labels)){const [min,max]=Physics.limits[k], step=k==='omega'?.005:.01;const div=document.createElement('div');div.className='parameter';div.innerHTML=`<label for="n-${k}">${lang==='ru'?r:e}<input id="n-${k}" type="number" min="${min}" max="${max}" step="${step}" value="${p[k]}"></label><input id="r-${k}" type="range" aria-label="${lang==='ru'?r:e}" min="${min}" max="${max}" step="${step}" value="${p[k]}">`;$('parameters').append(div);['n-','r-'].forEach(prefix=>$(prefix+k).addEventListener('change',event=>{const v=event.target.valueAsNumber;if(!Number.isFinite(v)||v<min||v>max){noticeKey='invalid';updateNotice();renderControls();return;}p[k]=v;reset(true);renderControls();}));}}
function updateNotice(){$('notice').textContent=noticeKey==='invalid'?text('Введите число в указанном диапазоне.','Enter a number within the allowed range.'):noticeKey==='exit'?text('Расчёт остановлен. Чтобы выйти, закройте вкладку браузера.','Simulation stopped. Close this browser tab to exit.'):noticeKey==='error'?text('Расчёт прерван из-за численной ошибки. Нажмите «Стоп».','Numerical error. Press Stop to reset.') :'';}
function updateStatus(){$('status').textContent=running?text('● Расчёт идёт','● Running'):model.t?text('Ⅱ Пауза','Ⅱ Paused'):text('○ Готов к запуску','○ Ready');$('pause').disabled=!running;}
function cancelSweep(){sweepToken++;sweeping=false;$('sweep').disabled=false;$('cancel').hidden=true;if(sweepState==='running')sweepState='cancelled';updateSweepStatus();}
function reset(clearSweep=false){model=new Physics.Model(p);history=[{t:0,x:model.x,v:0,drive:0}];noticeKey='';if(clearSweep){cancelSweep();sweepData=[];sweepState='idle';$('progress').hidden=true;$('exportSweep').disabled=true;updateSweepStatus();}updateStatus();updateNotice();draw();}
function route(){const hash=location.hash.slice(1),id=['home','lab','theory','authors'].includes(hash)?hash:'home';document.querySelectorAll('.page').forEach(e=>e.hidden=e.id!==id);document.querySelectorAll('nav a').forEach(e=>e.classList.toggle('active',e.hash==='#'+id));if(id!=='lab'){running=false;updateStatus();}draw();}
$('language').onclick=()=>{lang=lang==='ru'?'en':'ru';translate();};
$('start').onclick=()=>{running=true;updateStatus();};$('pause').onclick=()=>{running=false;updateStatus();};$('stop').onclick=()=>{running=false;reset();};
$('exit').onclick=()=>{running=false;cancelSweep();location.hash='home';noticeKey='exit';updateNotice();alert(text('Расчёт остановлен. Закройте вкладку браузера для выхода.','Simulation stopped. Close the browser tab to exit.'));};
$('seed').onchange=()=>{const v=$('seed').valueAsNumber;if(!Number.isInteger(v)||v<0||v>4294967295){$('seed').value=p.seed;noticeKey='invalid';updateNotice();return;}p.seed=v;reset(true);};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{p.D=Number(b.dataset.preset);reset(true);renderControls();});
window.addEventListener('hashchange',route);window.addEventListener('resize',draw);
// Canvas plots use CSS size and device pixel ratio; axes always carry numeric ticks.
function chart(id,xmin,xmax,ymin,ymax,xlabel,ylabel,right){const canvas=$(id),w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return null;const dpr=window.devicePixelRatio||1;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const c=canvas.getContext('2d');c.scale(dpr,dpr);const left=58,top=28,bottom=h-43,r=w-(right?65:22),X=x=>left+(x-xmin)/(xmax-xmin)*(r-left),Y=y=>bottom-(y-ymin)/(ymax-ymin)*(bottom-top);c.font='13px system-ui';c.lineWidth=1;for(let i=0;i<=4;i++){const x=xmin+(xmax-xmin)*i/4,y=ymin+(ymax-ymin)*i/4;c.strokeStyle='#293b4d';c.beginPath();c.moveTo(X(x),top);c.lineTo(X(x),bottom);c.moveTo(left,Y(y));c.lineTo(r,Y(y));c.stroke();c.fillStyle='#b2c4d4';c.textAlign='center';c.fillText(format(x),X(x),bottom+21);c.textAlign='right';c.fillText(format(y),left-9,Y(y)+4);if(right){c.textAlign='left';c.fillStyle='#ffb56b';c.fillText(format(right[0]+(right[1]-right[0])*i/4),r+9,Y(y)+4);}}c.fillStyle='#cbd9e5';c.textAlign='left';c.fillText(ylabel,4,17);c.textAlign='right';c.fillText(xlabel,r,h-3);if(right){c.fillStyle='#ffb56b';c.fillText('F [1]',w-3,17);}return {c,X,Y,left,top,right:r,bottom};}
function format(n){return Math.abs(n)>=100?n.toFixed(0):Number(n.toFixed(2)).toString();}
function line(g,points,color,width=2){const {c,X,Y}=g;c.save();c.beginPath();c.rect(g.left,g.top,g.right-g.left,g.bottom-g.top);c.clip();c.strokeStyle=color;c.lineWidth=width;c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(X(x),Y(y)):c.moveTo(X(x),Y(y)));c.stroke();c.restore();}
function draw(){if(!$('lab').hidden){const px=Math.max(2.6,Math.abs(model.x)+.2),pu=Physics.potential(model.x)-p.f*model.x*Math.sin(p.omega*model.t);let g=chart('potential',-px,px,-1.4,Math.max(2,pu+.4),'x [1]','U [1]');if(g){let pts=[];for(let x=-px;x<=px+.001;x+=.02)pts.push([x,Physics.potential(x)-p.f*x*Math.sin(p.omega*model.t)]);line(g,pts,'#49e2bc',3);const u=Physics.potential(model.x)-p.f*model.x*Math.sin(p.omega*model.t);g.c.fillStyle='#ffb56b';g.c.beginPath();g.c.arc(g.X(model.x),g.Y(u),9,0,Math.PI*2);g.c.fill();}const windowSize=6*Math.PI/p.omega,start=Math.max(0,model.t-windowSize);let extent=Math.max(2.5,...history.map(v=>Math.abs(v.x)));const F=Math.max(p.f,.01);g=chart('trajectory',start,Math.max(windowSize,model.t),-extent,extent,'t [1]','x [1]',[-F,F]);if(g){line(g,history.map(v=>[v.t,v.x]),'#49e2bc');line(g,history.map(v=>[v.t,v.drive/F*extent]),'#ffb56b',1.8);}$('time').textContent=model.t.toFixed(1);$('position').textContent=model.x.toFixed(2);$('transitions').textContent=model.transitions;let ymax=Math.max(.3,...sweepData.map(v=>v.amplitude+v.se))*1.2;g=chart('resonance',0,1.5,0,ymax,'D [1]','A [1]');if(g){if(sweepData.length){line(g,sweepData.map(v=>[v.D,v.amplitude]),'#49e2bc',3);for(const row of sweepData){const {c,X,Y}=g;c.strokeStyle='#9bd8c9';c.lineWidth=2;c.beginPath();c.moveTo(X(row.D),Y(Math.max(0,row.amplitude-row.se)));c.lineTo(X(row.D),Y(row.amplitude+row.se));c.stroke();for(const y of [Math.max(0,row.amplitude-row.se),row.amplitude+row.se]){c.beginPath();c.moveTo(X(row.D)-5,Y(y));c.lineTo(X(row.D)+5,Y(y));c.stroke();}c.fillStyle='#49e2bc';c.beginPath();c.arc(X(row.D),Y(row.amplitude),5,0,2*Math.PI);c.fill();}}else{g.c.fillStyle='#a8bacb';g.c.textAlign='center';g.c.fillText(text('Запустите измерение — здесь появятся результаты','Run the measurement to see results'),(g.left+g.right)/2,(g.top+g.bottom)/2);}}}}
let previous=0,accumulated=0;
function frame(now){const elapsed=Math.min((now-previous)/1000,.1);previous=now;if(running&&!document.hidden){accumulated+=elapsed*Number($('speed').value);const steps=Math.floor(accumulated);accumulated-=steps;try{for(let i=0;i<steps;i++){model.step();if(model.steps%5===0)history.push({t:model.t,x:model.x,v:model.v,drive:p.f*Math.sin(p.omega*model.t)});}const cutoff=model.t-6*Math.PI/p.omega;while(history.length&&history[0].t<cutoff)history.shift();}catch(e){running=false;noticeKey='error';updateNotice();updateStatus();}draw();}requestAnimationFrame(frame);}
function download(name,data){const url=URL.createObjectURL(new Blob(['\uFEFF'+data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function metadata(params){return '# model: inertial Langevin; covariance=2D delta; dimensionless\n'+Object.entries(params).map(([k,v])=>'# '+k+'='+v).join('\n')+'\n';}
$('export').onclick=()=>download('trajectory.csv',metadata(p)+'t,x,v,force\n'+history.map(v=>[v.t,v.x,v.v,v.drive].join(',')).join('\n'));
$('exportSweep').onclick=()=>download('resonance.csv',metadata(sweepParams)+'# periods=16; burn_periods=4; realizations=6; error=delta_method_SE\n# seed_ij=(seed+1009*i+7919*j) modulo 2^32\nD,amplitude,standard_error,n\n'+sweepData.map(v=>[v.D,v.amplitude,v.se,v.n].join(',')).join('\n'));
function updateSweepStatus(){let s='';if(sweepState==='running')s=text('Измерение: ','Measuring: ')+$('progress').value+'/72';if(sweepState==='cancelled')s=text('Отменено. Показаны только завершённые точки.','Cancelled. Only completed points are shown.');if(sweepState==='done'){const best=sweepData.reduce((a,b)=>a.amplitude>b.amplitude?a:b);s=text('Максимум на исследованной сетке: D = ','Maximum on the sampled grid: D = ')+best.D.toFixed(2)+', A = '+best.amplitude.toFixed(3)+' ± '+best.se.toFixed(3);} $('sweepStatus').textContent=s;}
// Chunked integration keeps file:// support and allows cancel / language / navigation.
async function measure(params,token){const m=new Physics.Model(params),T=2*Math.PI/params.omega,burn=Math.round(4*T/params.dt),n=Math.round(16*T/params.dt);let sin=0,cos=0;for(let i=0;i<burn+n;){if(token!==sweepToken)return null;const end=Math.min(i+12000,burn+n);for(;i<end;i++){m.step();if(i>=burn){sin+=m.x*Math.sin(params.omega*m.t);cos+=m.x*Math.cos(params.omega*m.t);}}await new Promise(resolve=>setTimeout(resolve,0));}return {sin:2*sin/n,cos:2*cos/n};}
$('sweep').onclick=async()=>{cancelSweep();const token=++sweepToken;sweeping=true;sweepState='running';sweepParams={...p};sweepData=[];$('progress').hidden=false;$('progress').value=0;$('exportSweep').disabled=true;$('sweep').disabled=true;$('cancel').hidden=false;updateSweepStatus();draw();const levels=[0,.025,.05,.1,.15,.22,.3,.42,.6,.85,1.1,1.5];try{for(let i=0;i<levels.length;i++){const samples=[];for(let j=0;j<6;j++){const r=await measure({...sweepParams,D:levels[i],seed:(sweepParams.seed+i*1009+j*7919)>>>0},token);if(!r||token!==sweepToken)return;samples.push(r);$('progress').value=i*6+j+1;updateSweepStatus();}sweepData.push({D:levels[i],...Physics.aggregate(samples)});$('exportSweep').disabled=false;draw();}sweeping=false;sweepState='done';$('sweep').disabled=false;$('cancel').hidden=true;updateSweepStatus();}catch(e){if(token===sweepToken){cancelSweep();noticeKey='error';updateNotice();}}};$('cancel').onclick=cancelSweep;
reset();translate();route();requestAnimationFrame(frame);
