/* Native MathML: accessible, scalable formulas, no fonts or libraries to download. */
function theory(lang) {
  const ru=lang==='ru';
  const equation=(label,body)=>`<div class="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="block" aria-label="${label}">${body.replaceAll('<mo>(</mo>','<mo stretchy="false">(</mo>').replaceAll('<mo>)</mo>','<mo stretchy="false">)</mo>')}</math></div>`;
  const potential=equation('U(x) = −a x²/2 + b x⁴/4', '<mi>U</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>=</mo><mo>−</mo><mfrac><mi>a</mi><mn>2</mn></mfrac><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><mfrac><mi>b</mi><mn>4</mn></mfrac><msup><mi>x</mi><mn>4</mn></msup>');
  const geometry=equation('x± = ±√(a/b); ΔU = a²/(4b)', '<msub><mi>x</mi><mo>±</mo></msub><mo>=</mo><mo>±</mo><msqrt><mfrac><mi>a</mi><mi>b</mi></mfrac></msqrt><mspace width="2em"/><mi>ΔU</mi><mo>=</mo><mfrac><msup><mi>a</mi><mn>2</mn></msup><mrow><mn>4</mn><mi>b</mi></mrow></mfrac>');
  const temperature=equation('D = γ T; ⟨ξ(t)ξ(t′)⟩ = 2 γ T δ(t−t′)', '<mi>D</mi><mo>=</mo><mi>γ</mi><mi>T</mi><mspace width="1em"/><mo>;</mo><mspace width="1em"/><mo>⟨</mo><mi>ξ</mi><mo>(</mo><mi>t</mi><mo>)</mo><mi>ξ</mi><mo>(</mo><msup><mi>t</mi><mo>′</mo></msup><mo>)</mo><mo>⟩</mo><mo>=</mo><mn>2</mn><mi>γ</mi><mi>T</mi><mi>δ</mi><mo>(</mo><mi>t</mi><mo>−</mo><msup><mi>t</mi><mo>′</mo></msup><mo>)</mo>');
  const dx=equation('dx = v dt', '<mi>d</mi><mi>x</mi><mo>=</mo><mi>v</mi><mi>d</mi><mi>t</mi>');
  const dv=equation('dv = (ax − bx³ − γv + F(t)) dt + √(2γT) dWₜ', '<mi>d</mi><mi>v</mi><mo>=</mo><mo>[</mo><mi>a</mi><mi>x</mi><mo>−</mo><mi>b</mi><msup><mi>x</mi><mn>3</mn></msup><mo>−</mo><mi>γ</mi><mi>v</mi><mo>+</mo><mi>F</mi><mo>(</mo><mi>t</mi><mo>)</mo><mo>]</mo><mi>d</mi><mi>t</mi><mo>+</mo><msqrt><mrow><mn>2</mn><mi>γ</mi><mi>T</mi></mrow></msqrt><mi>d</mi><msub><mi>W</mi><mi>t</mi></msub>');
  const tilt=equation('Ueff(x,t) = U(x) − xF(t)', '<msub><mi>U</mi><mtext>eff</mtext></msub><mo>(</mo><mi>x</mi><mo>,</mo><mi>t</mi><mo>)</mo><mo>=</mo><mi>U</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>−</mo><mi>x</mi><mi>F</mi><mo>(</mo><mi>t</mi><mo>)</mo>');
  return ru ? `
<h3>Температура, флуктуации и отклик</h3><p>Частица взаимодействует с термостатом: трение рассеивает энергию, а тепловые толчки сообщают её частице. При низкой температуре частица обычно остаётся в одной яме. При умеренной температуре тепловые переходы могут согласоваться со слабой периодической силой. При высокой температуре эта согласованность ухудшается. Максимум периодического отклика при промежуточной температуре — проявление стохастического резонанса.</p>
<h3>Изменяемая форма потенциала</h3>${potential}<p>Коэффициенты a и b управляют формой ям. При a &gt; 0 и b &gt; 0 положения минимумов и высота барьера равны:</p>${geometry}<p>Увеличение a при фиксированном b раздвигает и углубляет ямы; увеличение b при фиксированном a сближает ямы и уменьшает барьер. Исходному примеру соответствуют a = 1, b = 0,5. При a = 0, b &gt; 0 остаётся одна четвертичная яма; при a = b = 0 потенциал плоский. Комбинация a &gt; 0, b = 0 запрещена: потенциал не ограничен снизу. Для плоского случая сначала установите a = 0.</p>
<h3>Температура задаёт интенсивность шума</h3>${temperature}<p>Использованы безразмерные величины, масса и постоянная Больцмана равны единице. T — приведённая температура, не температура в кельвинах. В размерной записи D = γk<sub>B</sub>T. При выключенной силе и ограничивающем потенциале равновесная плотность пропорциональна exp[−(v²/2 + U(x))/T], а ⟨v²⟩ = T. Меняя γ при фиксированной T, мы меняем одновременно трение и интенсивность толчков, сохраняя температуру термостата. У плоского потенциала нет нормируемого равновесия по координате.</p>
<h3>Уравнения движения</h3>${dx}${dv}<p>W<sub>t</sub> — винеровский процесс. При включённой периодической силе F(t) = f sin(ωt), при выключенной F(t) = 0. Выключатель сохраняет выбранную амплитуду f. Значение f = 0 также выключает воздействие.</p>${tilt}<p>На рисунке показан мгновенный наклонённый потенциал, над ним — положение частицы на горизонтальной прямой. Пунктир связывает частицу с точкой на потенциале. Кнопка «Повернуть график» переключает ориентацию траектории и силы: по умолчанию время направлено вверх, координата вправо, как на схеме задания. Поворот не меняет данные. У силы своя подписанная шкала.</p>
` : `
<h3>Temperature, fluctuations and response</h3><p>A heat bath supplies random kicks while damping dissipates energy. Low temperature usually leaves the particle in one well. Moderate temperature can synchronize barrier crossings with a weak periodic force. At high temperature this synchronization deteriorates. An intermediate-temperature maximum of the periodic response demonstrates stochastic resonance.</p>
<h3>Adjustable potential</h3>${potential}<p>For a &gt; 0 and b &gt; 0 the minima and barrier height are:</p>${geometry}<p>Increasing a at fixed b separates and deepens the wells. Increasing b at fixed a brings the wells together and lowers the barrier. Defaults a = 1, b = 0.5 reproduce the original model. For a = 0, b &gt; 0 there is one quartic well; a = b = 0 gives a flat potential. The unbounded case a &gt; 0, b = 0 is rejected. Set a to zero first to explore the flat case.</p>
<h3>Temperature sets the noise intensity</h3>${temperature}<p>All quantities are dimensionless, with unit mass and Boltzmann constant. T is a reduced temperature, not kelvins. In dimensional form D = γk<sub>B</sub>T. With the drive off and a confining potential, the equilibrium density is proportional to exp[−(v²/2 + U(x))/T] and ⟨v²⟩ = T. Changing γ at fixed T changes both damping and noise intensity while preserving the bath temperature. A flat potential has no normalizable coordinate equilibrium.</p>
<h3>Equations of motion</h3>${dx}${dv}<p>W<sub>t</sub> is a Wiener process. The enabled force is F(t) = f sin(ωt); disabling it sets F(t) = 0 while retaining the chosen f. Setting f = 0 also removes the drive.</p>${tilt}<p>The plot shows the instantaneous tilted potential, with the particle moving on a horizontal track above it and a dashed projection to the potential. Rotate the trajectory and force by 90° without changing data: by default time increases upward and position to the right. The force has its own labeled scale.</p>
`;
}
