/* Native MathML: accessible, scalable formulas, no fonts or libraries to download. */
function theory(lang) {
  const ru=lang==='ru';
  const equation=(label,body)=>`<div class="equation"><math xmlns="http://www.w3.org/1998/Math/MathML" display="block" aria-label="${label}">${body.replaceAll('<mo>(</mo>','<mo stretchy="false">(</mo>').replaceAll('<mo>)</mo>','<mo stretchy="false">)</mo>')}</math></div>`;
  const potential=equation('U(x) = −a x²/2 + b x⁴/4', '<mi>U</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>=</mo><mo>−</mo><mfrac><mi>a</mi><mn>2</mn></mfrac><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><mfrac><mi>b</mi><mn>4</mn></mfrac><msup><mi>x</mi><mn>4</mn></msup>');
  const geometry=equation('x± = ±√(a/b); ΔU = a²/(4b)', '<msub><mi>x</mi><mo>±</mo></msub><mo>=</mo><mo>±</mo><msqrt><mfrac><mi>a</mi><mi>b</mi></mfrac></msqrt><mspace width="2em"/><mi>ΔU</mi><mo>=</mo><mfrac><msup><mi>a</mi><mn>2</mn></msup><mrow><mn>4</mn><mi>b</mi></mrow></mfrac>');
  const temperature=equation('D = γ T; ⟨ξ(t)ξ(t′)⟩ = 2 γ T δ(t−t′)', '<mi>D</mi><mo>=</mo><mi>γ</mi><mi>T</mi><mspace width="1em"/><mo>;</mo><mspace width="1em"/><mo>⟨</mo><mi>ξ</mi><mo>(</mo><mi>t</mi><mo>)</mo><mi>ξ</mi><mo>(</mo><msup><mi>t</mi><mo>′</mo></msup><mo>)</mo><mo>⟩</mo><mo>=</mo><mn>2</mn><mi>γ</mi><mi>T</mi><mi>δ</mi><mo>(</mo><mi>t</mi><mo>−</mo><msup><mi>t</mi><mo>′</mo></msup><mo>)</mo>');
  const dx=equation('dx = v dt', '<mi>d</mi><mi>x</mi><mo>=</mo><mi>v</mi><mi>d</mi><mi>t</mi>');
  const dv=equation('dv = (ax − bx³ − γv + F(t)) dt + √(2γT) dWₜ', '<mi>d</mi><mi>v</mi><mo>=</mo><mo>[</mo><mi>a</mi><mi>x</mi><mo>−</mo><mi>b</mi><msup><mi>x</mi><mn>3</mn></msup><mo>−</mo><mi>γ</mi><mi>v</mi><mo>+</mo><mi>F</mi><mo>(</mo><mi>t</mi><mo>)</mo><mo>]</mo><mi>d</mi><mi>t</mi><mo>+</mo><msqrt><mrow><mn>2</mn><mi>γ</mi><mi>T</mi></mrow></msqrt><mi>d</mi><msub><mi>W</mi><mi>t</mi></msub>');
  const tilt=equation('Ueff(x,t) = U(x) − xF(t)', '<msub><mi>U</mi><mtext>eff</mtext></msub><mo>(</mo><mi>x</mi><mo>,</mo><mi>t</mi><mo>)</mo><mo>=</mo><mi>U</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>−</mo><mi>x</mi><mi>F</mi><mo>(</mo><mi>t</mi><mo>)</mo>');
  const critical=equation('fc = (2a/3)√(a/(3b))', '<msub><mi>f</mi><mi>c</mi></msub><mo>=</mo><mfrac><mrow><mn>2</mn><mi>a</mi></mrow><mn>3</mn></mfrac><msqrt><mfrac><mi>a</mi><mrow><mn>3</mn><mi>b</mi></mrow></mfrac></msqrt>');
  const time=equation('τK ≈ 2πγ/(√2 a) exp(ΔU/T) ≈ P/2; P = 2π/ω', '<msub><mi>τ</mi><mi>K</mi></msub><mo>≈</mo><mfrac><mrow><mn>2</mn><mi>π</mi><mi>γ</mi></mrow><mrow><msqrt><mn>2</mn></msqrt><mi>a</mi></mrow></mfrac><mo>exp</mo><mo>(</mo><mfrac><mi>ΔU</mi><mi>T</mi></mfrac><mo>)</mo><mo>≈</mo><mfrac><mi>P</mi><mn>2</mn></mfrac><mspace width="1em"/><mo>;</mo><mi>P</mi><mo>=</mo><mfrac><mrow><mn>2</mn><mi>π</mi></mrow><mi>ω</mi></mfrac>');
  const coeff=(name,trig)=>equation(`${name}j = (2/L) ∫ xj(t) ${trig}(ωt) dt`, `<msub><mi>${name}</mi><mi>j</mi></msub><mo>=</mo><mfrac><mn>2</mn><mi>L</mi></mfrac><msubsup><mo>∫</mo><msub><mi>t</mi><mn>0</mn></msub><mrow><msub><mi>t</mi><mn>0</mn></msub><mo>+</mo><mi>L</mi></mrow></msubsup><msub><mi>x</mi><mi>j</mi></msub><mo>(</mo><mi>t</mi><mo>)</mo><mo>${trig}</mo><mo>(</mo><mi>ω</mi><mi>t</mi><mo>)</mo><mi>d</mi><mi>t</mi>`);
  const amplitude=equation('A = √(⟨S⟩² + ⟨C⟩²)', '<mi>A</mi><mo>=</mo><msqrt><mrow><msup><mrow><mo>⟨</mo><mi>S</mi><mo>⟩</mo></mrow><mn>2</mn></msup><mo>+</mo><msup><mrow><mo>⟨</mo><mi>C</mi><mo>⟩</mo></mrow><mn>2</mn></msup></mrow></msqrt>');
  return ru ? `
<h3>Температура, флуктуации и отклик</h3><p>Частица взаимодействует с термостатом: трение рассеивает энергию, а тепловые толчки сообщают её частице. При низкой температуре частица обычно остаётся в одной яме. При умеренной температуре тепловые переходы могут согласоваться со слабой периодической силой. При высокой температуре эта согласованность ухудшается. Максимум периодического отклика при промежуточной температуре — проявление стохастического резонанса.</p>
<h3>Изменяемая форма потенциала</h3>${potential}<p>Коэффициенты a и b управляют формой ям. При a &gt; 0 и b &gt; 0 положения минимумов и высота барьера равны:</p>${geometry}<p>Увеличение a при фиксированном b раздвигает и углубляет ямы; увеличение b при фиксированном a сближает ямы и уменьшает барьер. Исходному примеру соответствуют a = 1, b = 0,5. При a = 0, b &gt; 0 остаётся одна четвертичная яма; при a = b = 0 потенциал плоский. Комбинация a &gt; 0, b = 0 запрещена: потенциал не ограничен снизу. Для плоского случая сначала установите a = 0.</p>
<h3>Температура задаёт интенсивность шума</h3>${temperature}<p>Использованы безразмерные величины, масса и постоянная Больцмана равны единице. T — приведённая температура, не температура в кельвинах. В размерной записи D = γk<sub>B</sub>T. При выключенной силе и ограничивающем потенциале равновесная плотность пропорциональна exp[−(v²/2 + U(x))/T], а ⟨v²⟩ = T. Меняя γ при фиксированной T, мы меняем одновременно трение и интенсивность толчков, сохраняя температуру термостата. У плоского потенциала нет нормируемого равновесия по координате.</p>
<h3>Уравнения движения</h3>${dx}${dv}<p>W<sub>t</sub> — винеровский процесс. При включённой периодической силе F(t) = f sin(ωt), при выключенной F(t) = 0. Выключатель сохраняет выбранную амплитуду f. Значение f = 0 также выключает воздействие.</p>${tilt}<p>На рисунке показан мгновенный наклонённый потенциал, над ним — положение частицы на горизонтальной прямой. Пунктир связывает частицу с точкой на потенциале. Кнопка «Повернуть график» переключает ориентацию траектории и силы: по умолчанию время направлено вверх, координата вправо, как на схеме задания. Поворот не меняет данные. У силы своя подписанная шкала.</p>
<h3>Когда сохраняются две ямы?</h3>${critical}<p>Для a,b &gt; 0 две мгновенные ямы существуют при |F(t)| &lt; f<sub>c</sub>. Если f ≥ f<sub>c</sub>, сила может сама устранять барьер: такой режим нельзя безоговорочно интерпретировать как усиление подпорогового сигнала шумом. Приложение сообщает об этом. Даже при f &lt; f<sub>c</sub> инерционная динамика иногда допускает переходы без шума.</p>
<h3>Времена переходов</h3>${time}<p>Формула Крамерса — оценка для неподвижного двухъямного потенциала, сильного трения и T ≪ ΔU. Равенство времени перехода половине периода — качественный ориентир резонанса, а не точное условие для всех параметров. При умеренном трении префактор неточен. Кривая в приложении получается моделированием, а не подстановкой в эту формулу.</p>
<h3>Измерение периодического отклика</h3>${coeff('S','sin')}${coeff('C','cos')}${amplitude}<p>Здесь t<sub>0</sub> = 4P — разогрев, L = 16P — интервал измерения; T по-прежнему обозначает только температуру. Коэффициенты S и C усредняются по 6 независимым реализациям для каждой из 12 температур. Усы — стандартная ошибка амплитуды по дельта-методу (приближённая около нулевого отклика). Это амплитуда среднего отклика, не отношение сигнал/шум. Максимум на сетке не определяет точный оптимум. При выключенной силе, f = 0 или отсутствии двух ям измерение резонанса недоступно.</p>
<h3>Численный метод и демонстрация</h3><p>BAOAB с шагом Δt = 0,02 включает точный шаг Орнштейна—Уленбека: v ← exp(−γΔt)v + √[T(1 − exp(−2γΔt))]N(0,1). Быстрый темп меняет только число шагов в секунду. Для воспроизводимости используется зерно генератора. Межъямные переходы считаются по порогам ±½√(a/b); при a = 0 счётчик не применяется.</p><ol><li>Начните с T = 0 и включённой слабой силы: частица колеблется внутри ямы.</li><li>Повысьте температуру и наблюдайте согласование переходов с силой.</li><li>Выключите силу, чтобы сравнить с чисто тепловым движением.</li><li>Измените a и b, оцените новый барьер, затем включите силу и измерьте отклик от температуры.</li></ol>` : `
<h3>Temperature, fluctuations and response</h3><p>A heat bath supplies random kicks while damping dissipates energy. Low temperature usually leaves the particle in one well. Moderate temperature can synchronize barrier crossings with a weak periodic force. At high temperature this synchronization deteriorates. An intermediate-temperature maximum of the periodic response demonstrates stochastic resonance.</p>
<h3>Adjustable potential</h3>${potential}<p>For a &gt; 0 and b &gt; 0 the minima and barrier height are:</p>${geometry}<p>Increasing a at fixed b separates and deepens the wells. Increasing b at fixed a brings the wells together and lowers the barrier. Defaults a = 1, b = 0.5 reproduce the original model. For a = 0, b &gt; 0 there is one quartic well; a = b = 0 gives a flat potential. The unbounded case a &gt; 0, b = 0 is rejected. Set a to zero first to explore the flat case.</p>
<h3>Temperature sets the noise intensity</h3>${temperature}<p>All quantities are dimensionless, with unit mass and Boltzmann constant. T is a reduced temperature, not kelvins. In dimensional form D = γk<sub>B</sub>T. With the drive off and a confining potential, the equilibrium density is proportional to exp[−(v²/2 + U(x))/T] and ⟨v²⟩ = T. Changing γ at fixed T changes both damping and noise intensity while preserving the bath temperature. A flat potential has no normalizable coordinate equilibrium.</p>
<h3>Equations of motion</h3>${dx}${dv}<p>W<sub>t</sub> is a Wiener process. The enabled force is F(t) = f sin(ωt); disabling it sets F(t) = 0 while retaining the chosen f. Setting f = 0 also removes the drive.</p>${tilt}<p>The plot shows the instantaneous tilted potential, with the particle moving on a horizontal track above it and a dashed projection to the potential. Rotate the trajectory and force by 90° without changing data: by default time increases upward and position to the right. The force has its own labeled scale.</p>
<h3>When do both wells survive?</h3>${critical}<p>For a,b &gt; 0 the instantaneous potential has two wells if |F(t)| &lt; f<sub>c</sub>. When f ≥ f<sub>c</sub>, the drive can remove the barrier without noise, so the interpretation as noise-assisted subthreshold response needs care. The app flags this regime. Inertial dynamics may permit deterministic transitions even below the static threshold.</p>
<h3>Transition times</h3>${time}<p>The Kramers estimate assumes an unforced double well, strong damping and T ≪ ΔU. Matching the transition time to half a drive period is a qualitative resonance guide. At moderate damping the prefactor is inaccurate. The app measures trajectories rather than plotting this approximation.</p>
<h3>Periodic response measurement</h3>${coeff('S','sin')}${coeff('C','cos')}${amplitude}<p>Here t<sub>0</sub> = 4P is warm-up and L = 16P is the measurement interval; T denotes temperature only. Average S and C over 6 independent realizations at each of 12 temperatures. Whiskers show delta-method standard errors, approximate near zero response. This is the amplitude of the ensemble mean, not SNR; a sampled maximum is not an exact optimum. Resonance measurement is unavailable with the drive off, f = 0 or without two wells.</p>
<h3>Numerics and demonstration</h3><p>BAOAB uses Δt = 0.02 and an exact Ornstein–Uhlenbeck step: v ← exp(−γΔt)v + √[T(1 − exp(−2γΔt))]N(0,1). Fast playback changes only the steps per second. A seeded generator makes runs reproducible. Transition thresholds are ±½√(a/b); transitions are not counted for a = 0.</p><ol><li>Start at T = 0 with the weak drive enabled.</li><li>Increase temperature and observe transitions relative to the force.</li><li>Disable the drive to compare with purely thermal motion.</li><li>Change a and b, inspect the new barrier, enable the drive and measure the temperature response.</li></ol>`;
}
