// Optional development check: requires Playwright and a Chromium executable.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const os=require('node:os');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:8765/'))requests.push(r.url());});
 await page.goto(process.env.TEST_URL || 'file://'+path.resolve(__dirname,'../index.html'));
 await page.screenshot({path:path.join(os.tmpdir(),'resonance-home.png'),fullPage:true});
 await page.click('#home a[href="#lab"]');await page.click('#start');await page.waitForTimeout(700);await page.click('#pause');
 let t=Number(await page.locator('#time').textContent());assert.ok(t>0);await page.waitForTimeout(200);assert.equal(Number(await page.locator('#time').textContent()),t);
 await page.fill('#n-T','.3');await page.locator('#n-T').dispatchEvent('change');assert.equal(await page.locator('#time').textContent(),'0.0');
 await page.fill('#n-T','-1');await page.locator('#n-T').dispatchEvent('change');assert.equal(await page.inputValue('#n-T'),'0.3');assert.ok(await page.locator('#notice').textContent());
 await page.click('[data-preset="0.22"]');await page.selectOption('#speed','1500');await page.click('#start');await page.waitForTimeout(1500);await page.click('#pause');
 await page.screenshot({path:path.join(os.tmpdir(),'resonance-lab.png'),fullPage:true});

 assert.equal(await page.locator('#trajectory').getAttribute('data-orientation'),'vertical');
 const before=await page.evaluate(()=>({t:model.t,x:model.x,history:history.length}));
 await page.click('#rotate');assert.equal(await page.locator('#trajectory').getAttribute('data-orientation'),'horizontal');
 assert.deepEqual(await page.evaluate(()=>({t:model.t,x:model.x,history:history.length})),before);
 await page.click('#rotate');
 await page.uncheck('#driveEnabled');assert.ok(await page.isDisabled('#n-f'));
 assert.equal(await page.evaluate(()=>Physics.drive(10,p)),0);
 await page.check('#driveEnabled');assert.equal(await page.inputValue('#n-f'),'0.18');
 await page.fill('#n-a','2');await page.locator('#n-a').dispatchEvent('change');
 assert.ok((await page.locator('#shapeInfo').textContent()).includes('2.000'));
 await page.fill('#n-b','0');await page.locator('#n-b').dispatchEvent('change');assert.equal(await page.inputValue('#n-b'),'0.5');
 await page.fill('#n-a','0');await page.locator('#n-a').dispatchEvent('change');
 await page.fill('#n-b','0');await page.locator('#n-b').dispatchEvent('change');assert.equal(await page.evaluate(()=>model.x),0);
 await page.fill('#n-b','0.5');await page.locator('#n-b').dispatchEvent('change');
 await page.fill('#n-a','1');await page.locator('#n-a').dispatchEvent('change');
 await page.fill('#n-gamma','2');await page.locator('#n-gamma').dispatchEvent('change');
 assert.ok((await page.locator('#thermalInfo').textContent()).includes('0.440'));
 await page.fill('#n-gamma','1');await page.locator('#n-gamma').dispatchEvent('change');
 await page.click('#language');assert.equal(await page.locator('html').getAttribute('lang'),'en');assert.equal(await page.locator('#start').textContent(),'Start');
 await page.click('nav a[href="#theory"]');assert.deepEqual(await page.locator('#theoryContent h3').allTextContents(),['Temperature, fluctuations and response','Adjustable potential','Temperature sets the noise intensity','Equations of motion']);assert.equal(await page.locator('math').count(),6);await page.screenshot({path:path.join(os.tmpdir(),'resonance-theory.png'),fullPage:true});
 await page.click('nav a[href="#authors"]');assert.ok((await page.locator('#authors').textContent()).includes('Stanislav Kapitonov'));assert.ok(!(await page.locator('#authors').textContent()).includes('supervisor'));await page.screenshot({path:path.join(os.tmpdir(),'resonance-authors.png'),fullPage:true});
 await page.click('nav a[href="#lab"]');
 assert.equal(await page.locator('#lab canvas').count(),2);
 assert.equal(await page.locator('#sweep, #resonance, #exportSweep, #progress, #cancel').count(),0);
 const downloadPromise=page.waitForEvent('download');await page.click('#export');const download=await downloadPromise;assert.equal(download.suggestedFilename(),'trajectory.csv');await download.saveAs(path.join(os.tmpdir(),'trajectory.csv'));
 await page.click('nav a[href="#theory"]');await page.click('#language');
 assert.deepEqual(await page.locator('#theoryContent h3').allTextContents(),['Температура, флуктуации и отклик','Изменяемая форма потенциала','Температура задаёт интенсивность шума','Уравнения движения']);
 assert.equal(await page.locator('math').count(),6);
 await page.click('nav a[href="#lab"]');await page.click('#language');
 await page.click('#language');await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(os.tmpdir(),'resonance-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.click('#stop');assert.equal(await page.locator('#time').textContent(),'0.0');
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);console.log('Browser checks passed: controls, RU/EN, shortened theory, trajectory CSV, mobile, no network, no console errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
